version: '3.7'
services:
  apache:
    container_name: apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./httpd.conf:/etc/apache2/httpd.conf
      - ./html:/var/www/localhost/htdocs/
    networks:
      - docker-network
    environment: 
      - server_name=jetpackbridge.runonflux.io
networks:
  docker-network:
    driver: bridge
